### PR TITLE
closes #130 - look in /usr/local/opt/openssl on osx for openssl libs

### LINKED ISSUE #130: Mac OS X compilation problems (-lssl, duplicate symbol errors)
2.200002 and also 2.200001 do not compile on my Mac OS X 10.11 system. First problem is that -lssl and -lcrypto exist in the base system, but this is not openssl, so there's no openssl/conf.h. A sample report may be seen here: http://www.cpantesters.org/cpan/report/55588950-916d-11e6-a0b4-8987b9648b83

I can workaround this by adding -L/usr/local/opt/openssl/lib and -I/usr/local/opt/openssl/include to use a homebrew-installed openssl (probably another approach would be to disable ssl here).

Then the next error happens:
```
LD_RUN_PATH="/usr/local/Cellar/openssl/1.0.2h_1/lib" cc  -mmacosx-version-min=10.11 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector RabbitMQ.o amqp_api.o amqp_connection.o amqp_consumer.o amqp_framing.o amqp_hostcheck.o amqp_mem.o amqp_openssl.o amqp_socket.o amqp_table.o amqp_tcp_socket.o amqp_time.o amqp_url.o perl_math_int64.o RabbitMQ.o   -o blib/arch/auto/Net/AMQP/RabbitMQ/RabbitMQ.bundle  \
           -L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl -lcrypto   \
          
duplicate symbol _array_to_amqp_array in:
    RabbitMQ.o
duplicate symbol _amqp_kind_for_sv in:
    RabbitMQ.o
duplicate symbol _die_on_amqp_error in:
    RabbitMQ.o
...
```

This can be fixed by removing the 2nd RabbitMQ.p from the linker line.

With these changes all tests pass (at least with 2.200002).

### PR DESCRIPTION
**Pull request by markwellis**
otherwise disable ssl on sx

### CODE REVIEW

**Comment by markwellis** [comment]
I tested this best I could with a dodgey osx seirra vm. It seems to work ok, as in it only compiles with ssl support if openssl is in the /usr/local/opt/openssl dir
