### ISSUE TITLE
Mac OS X compilation problems (-lssl, duplicate symbol errors)

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#130]
2.200002 and also 2.200001 do not compile on my Mac OS X 10.11 system. First problem is that -lssl and -lcrypto exist in the base system, but this is not openssl, so there's no openssl/conf.h. A sample report may be seen here: http://www.cpantesters.org/cpan/report/55588950-916d-11e6-a0b4-8987b9648b83

I can workaround this by adding -L/usr/local/opt/openssl/lib and -I/usr/local/opt/openssl/include to use a homebrew-installed openssl (probably another approach would be to disable ssl here).

Then the next error happens:
```
LD_RUN_PATH="/usr/local/Cellar/openssl/1.0.2h_1/lib" cc  -mmacosx-version-min=10.11 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector RabbitMQ.o amqp_api.o amqp_connection.o amqp_consumer.o amqp_framing.o amqp_hostcheck.o amqp_mem.o amqp_openssl.o amqp_socket.o amqp_table.o amqp_tcp_socket.o amqp_time.o amqp_url.o perl_math_int64.o RabbitMQ.o   -o blib/arch/auto/Net/AMQP/RabbitMQ/RabbitMQ.bundle  \
           -L/usr/local/Cellar/openssl/1.0.2h_1/lib -lssl -lcrypto   \
          
duplicate symbol _array_to_amqp_array in:
    RabbitMQ.o
duplicate symbol _amqp_kind_for_sv in:
    RabbitMQ.o
duplicate symbol _die_on_amqp_error in:
    RabbitMQ.o
...
```

This can be fixed by removing the 2nd RabbitMQ.p from the linker line.

With these changes all tests pass (at least with 2.200002).

**Comment by eserte** [comment]
The changes I did, just as a base for discussions (e.g. one could decide to not use ssl at all here):
```
diff --git i/Makefile.PL w/Makefile.PL
index 71026ef..89af82a 100644
--- i/Makefile.PL
+++ w/Makefile.PL
@@ -35,12 +35,18 @@ my $has_openssl = check_lib(
 if ( $has_openssl ) {
     push @defines, '-DNAR_HAVE_OPENSSL';
     push @libs, '-lssl', '-lcrypto';
+    if ( $^O eq 'darwin') {
+        unshift @libs, '-L/usr/local/opt/openssl/lib';
+    }
     if ( $^O eq 'MSWin32' ) {
         push @inc, "-Irabbitmq-include/win32";
     }
     else {
         push @inc, "-Irabbitmq-include/unix";
     }
+    if ( $^O eq 'darwin') {
+        unshift @inc, '-I/usr/local/opt/openssl/include';
+    }
 }
 
 my $ofiles = '';
@@ -52,6 +58,10 @@ foreach ( <*.c> ){
     $_ =~ s/.c$/.o/;
     $ofiles .= "$_ ";
 }
+if ( $^O eq 'darwin' ) {
+    # avoid "duplicate symbol" errors
+    $ofiles =~ s{RabbitMQ\.o}{};
+}
 
 my %WriteMakefileArgs = (
     NAME            => 'Net::AMQP::RabbitMQ',
```

**Comment by markwellis** [comment]
hmm, you shouldn't have the second RabbitMQ.o, unless it's being found by the Makefile.PL, which shouldn't happen unless the build dir is not clean.

Is the build dir clean? I can also try to detect OSX and disable ssl unless it can find the real openssl libs and not Apple's version

**Comment by markwellis** [comment]
Yeah as you just sent. Except there shouldn't be a RabbitMQ.c to find because the XS compiler hasn't run yet, unless the dir is not clean. But even if it is it's not a valid reason to fail, so the patch looks good.

Feel free to send a PR, or I'll do it tonight

**Comment by eserte** [comment]
OK, the duplicate RabbitMQ.o happens only if I run Makefile.PL a second time (which happened during my fixing).

**Comment by markwellis** [comment]
Hmm, it will also need to NOT include the apple ssl lib, if openssl is not installed. Then it will build without openssl support. Also, IIRC this is only an issue on newer OSX's.  https://developer.apple.com/library/content/documentation/Security/Conceptual/cryptoservices/GeneralPurposeCrypto/GeneralPurposeCrypto.html looks like OSx 10.5+

**Comment by markwellis** [comment]
Fixed in version 2.30000, which will be on cpan shortly
